
import turtle
wn=turtle.Screen()
t1=turtle.Turtle()
turnBy=45
def giyuk(size):
	t1.fd(size)
	t1.right(90)
	t1.fd(size)

	
t1.home()
t1.clear()
turnBy=45
size=100
oldPos=t1.pos()
oldHead=t1.heading()
giyuk(size)
t1.penup()
t1.setpos(oldPos)
t1.setheading(oldHead+turnBy)
t1.pendown()
giyuk(size)
t1.penup()
t1.setpos(oldPos)
t1.setheading(oldHead+turnBy)
t1.setheading(oldHead+90)
giyuk(size)
t1.setpos(oldPos)
t1.pendown()
t1.setheading(oldHead+90)
giyuk(size)
t1.penup()
t1.setpos(oldPos)
t1.setheading(oldHead+135)
giyuk(size)
t1.setpos(oldPos)
t1.pendown()
t1.setheading(oldHead+135)
giyuk(size)
t1.penup()
t1.setpos(oldPos)
t1.setheading(oldHead+180)
t1.pendown()
giyuk(size)
t1.penup()
t1.setpos(oldPos)
t1.setheading(oldHead+225)
t1.pendown()
giyuk(size)
t1.penup()
t1.setpos(oldPos)
t1.setheading(oldHead+270)
t1.pendown()
giyuk(size)
t1.penup()
t1.setpos(oldPos)
t1.setheading(oldHead+270+45)
t1.pendown()
giyuk(size)
 